# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x11messari.common.v1\"\xbd\x01\n\x0bTransaction\x12\x12\n\x04hash\x18\x01 \x01(\tR\x04hash\x12\x14\n\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12!\n\x0c\x62lock_number\x18\x03 \x01(\x04R\x0b\x62lockNumber\x12\'\n\x0f\x62lock_timestamp\x18\x04 \x01(\x04R\x0e\x62lockTimestamp\x12\x1b\n\tgas_price\x18\x05 \x01(\tR\x08gasPrice\x12\x1b\n\tgas_limit\x18\x06 \x01(\x04R\x08gasLimit\"#\n\x07\x41\x64\x64ress\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\"=\n\tAddresses\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32\x1a.messari.common.v1.AddressR\x05itemsb\x06proto3')



_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_ADDRESSES = DESCRIPTOR.message_types_by_name['Addresses']
Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:messari.common.v1.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:messari.common.v1.Address)
  })
_sym_db.RegisterMessage(Address)

Addresses = _reflection.GeneratedProtocolMessageType('Addresses', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSES,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:messari.common.v1.Addresses)
  })
_sym_db.RegisterMessage(Addresses)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTION._serialized_start=36
  _TRANSACTION._serialized_end=225
  _ADDRESS._serialized_start=227
  _ADDRESS._serialized_end=262
  _ADDRESSES._serialized_start=264
  _ADDRESSES._serialized_end=325
# @@protoc_insertion_point(module_scope)
